version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/node-app/docker-node-sample
      - /opt/node-app/docker-node-sample/node_modules